[package]
name = "scryfall"
version = "0.1.0"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2018"
description = "A wrapper around the scryfall magic the gathering api"
license = "MIT"

[dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
reqwest = "*"
chrono = { version = "0.4", features = ["serde"] }
